# Generated by Django 2.0.13 on 2019-05-22 15:13

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='judgefiles', verbose_name='签单文件')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件名')),
            ],
            options={
                'verbose_name': '签单文件表',
                'verbose_name_plural': '签单文件表',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Signs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='待审批签单名')),
                ('createDate', models.DateField(verbose_name='行文日期')),
                ('createAca', models.CharField(default='软件学院', max_length=100, verbose_name='行文单位')),
                ('director', models.CharField(max_length=100, verbose_name='签单负责人')),
                ('info', models.TextField(verbose_name='事项内容')),
                ('dep_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='部门负责人')),
                ('dep_opinion', models.TextField(blank=True, null=True, verbose_name='部门负责人意见')),
                ('office_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='两办负责人')),
                ('office_opinion', models.TextField(blank=True, null=True, verbose_name='两办负责人意见')),
                ('relate_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='相关部门负责人')),
                ('relate_opinion', models.TextField(blank=True, null=True, verbose_name='相关部门负责人意见')),
                ('vice_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='分管校领导')),
                ('vice_opinion', models.TextField(blank=True, null=True, verbose_name='分管校领导意见')),
                ('aca_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='校领导')),
                ('aca_opinion', models.TextField(blank=True, null=True, verbose_name='校领导会签意见')),
                ('file', models.ManyToManyField(related_name='files', to='approval.JudgeFiles', verbose_name='相关附件')),
            ],
            options={
                'verbose_name': '签单',
                'verbose_name_plural': '签单',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
