# Generated by Django 2.0.13 on 2019-06-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signs',
            name='aca_judge',
            field=models.CharField(blank=True, choices=[('通过', '通过'), ('否决', '否决')], max_length=5, null=True, verbose_name='校领导会签结果'),
        ),
        migrations.AddField(
            model_name='signs',
            name='dep_judge',
            field=models.CharField(blank=True, choices=[('通过', '通过'), ('否决', '否决')], max_length=5, null=True, verbose_name='部门负责人审批结果'),
        ),
        migrations.AddField(
            model_name='signs',
            name='office_judge',
            field=models.CharField(blank=True, choices=[('通过', '通过'), ('否决', '否决')], max_length=5, null=True, verbose_name='两办负责人审批结果'),
        ),
        migrations.AddField(
            model_name='signs',
            name='relate_judge',
            field=models.CharField(blank=True, choices=[('通过', '通过'), ('否决', '否决')], max_length=5, null=True, verbose_name='相关部门负责人审批结果'),
        ),
        migrations.AddField(
            model_name='signs',
            name='vice_judge',
            field=models.CharField(blank=True, choices=[('通过', '通过'), ('否决', '否决')], max_length=5, null=True, verbose_name='分管校领导审批结果'),
        ),
    ]
