# Generated by Django 2.0.13 on 2019-06-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0002_auto_20190617_1052'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='signs',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='signs',
            name='file',
            field=models.ManyToManyField(blank=True, null=True, related_name='files', to='approval.JudgeFiles', verbose_name='相关附件'),
        ),
    ]
