# Generated by Django 2.0.13 on 2019-06-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_auto_20190617_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='signs',
            name='status_code',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='状态码'),
        ),
    ]
