# Generated by Django 2.0.13 on 2020-08-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_signs_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signs',
            name='file',
            field=models.ManyToManyField(blank=True, related_name='files', to='approval.JudgeFiles', verbose_name='相关附件'),
        ),
    ]
