# Generated by Django 2.0.13 on 2020-01-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_allow',
            name='card_id',
            field=models.CharField(default=1, max_length=20, verbose_name='消费卡号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal_allow',
            name='location',
            field=models.CharField(default=1, max_length=30, verbose_name='消费地点'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='personal_is_marry',
            field=models.CharField(choices=[('未婚', '未婚'), ('已婚', '已婚'), ('丧偶', '丧偶'), ('离异', '离异')], max_length=4, verbose_name='婚姻情况'),
        ),
    ]
