# Generated by Django 2.0.13 on 2020-01-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20200103_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='edu_collage_school',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='专科毕业院校及时间'),
        ),
        migrations.AddField(
            model_name='staff',
            name='edu_doctor_school',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='博士毕业院校及时间'),
        ),
        migrations.AddField(
            model_name='staff',
            name='edu_graduate_school',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='研究生毕业院校及时间'),
        ),
        migrations.AddField(
            model_name='staff',
            name='edu_master_school',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='硕士毕业院校及时间'),
        ),
        migrations.AddField(
            model_name='staff',
            name='edu_postdoctor_school',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='博士后毕业院校及时间'),
        ),
        migrations.AddField(
            model_name='staff',
            name='edu_undergraduate_school',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='本科毕业院校及时间'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='personal_birth_date',
            field=models.CharField(max_length=128, verbose_name='出生日期'),
        ),
    ]
