# Generated by Django 2.0.13 on 2020-01-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_auto_20200103_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='work_dismiss_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='离职时间'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='work_duty_hire_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='职务聘用时间'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='work_enter_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='work_hire_rank_aca_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='院编员工职称聘用时间'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='work_set_rank_date',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='职称评定时间'),
        ),
    ]
