# Generated by Django 2.0.13 on 2020-01-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_auto_20200103_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='edu_grade',
            field=models.CharField(blank=True, choices=[('本科', '本科'), ('硕士', '硕士'), ('博士', '博士'), ('专科', '专科'), ('其他', '其他')], max_length=5, null=True, verbose_name='学位'),
        ),
    ]
