# Generated by Django 2.0.13 on 2020-01-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_auto_20200103_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='edu_background',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='学历'),
        ),
    ]
