# Generated by Django 2.0.13 on 2020-01-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_auto_20200103_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='work_duty',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='行政职务'),
        ),
    ]
