# Generated by Django 2.2 on 2020-06-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_auto_20200103_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='personal_duty_num',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='考勤号'),
        ),
        migrations.AddField(
            model_name='staff',
            name='personal_salery_num',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='工资号'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='at_post',
            field=models.CharField(choices=[('在职', '在职'), ('离职', '离职'), ('请长假', '请长假'), ('访学', '访学'), ('退休', '退休'), ('借调', '借调'), ('进修', '进修'), ('其他', '其他')], max_length=10, verbose_name='职工状态'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='edu_grade',
            field=models.CharField(blank=True, choices=[('学士', '学士'), ('硕士', '硕士'), ('博士', '博士'), ('专科', '专科'), ('其他', '其他')], max_length=5, null=True, verbose_name='学位'),
        ),
    ]
