# Generated by Django 2.0.13 on 2020-08-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_auto_20200612_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='edu_graduate_school',
        ),
        migrations.AddField(
            model_name='staff',
            name='personal_state',
            field=models.CharField(choices=[('在职', '在职'), ('离休', '离休'), ('退休', '退休'), ('内退返岗', '内退返岗'), ('内退', '内退'), ('调离', '调离'), ('辞职', '辞职'), ('自动离职', '自动离职'), ('开除', '开除'), ('去世', '去世'), ('解聘', '解聘'), ('疾病不在岗', '疾病不在岗'), ('疾病在岗', '疾病在岗'), ('哺乳假', '哺乳假'), ('拟调离', '拟调离'), ('内部退养', '内部退养'), ('境内研修', '境内研修'), ('挂校人才中心', '挂校人才中心'), ('延聘人员', '延聘人员'), ('离岗待退', '离岗待退'), ('境外研修', '境外研修'), ('借调挂职', '借调挂职'), ('短期用工', '短期用工'), ('病事假', '病事假'), ('停职创办企业', '停职创办企业'), ('其他', '其他'), ('逾期未归', '逾期未归'), ('返聘人员', '返聘人员'), ('异地任职', '异地任职'), ('产假', '产假'), ('后勤集团返岗', '后勤集团返岗')], default='在职', max_length=10, verbose_name='职工状态'),
        ),
        migrations.AddField(
            model_name='staff',
            name='work_title_type',
            field=models.CharField(blank=True, choices=[('正高', '正高'), ('副高', '副高'), ('中级', '中级'), ('助理', '助理'), ('员级', '员级'), ('初期博', '初期博'), ('初期硕', '初期硕'), ('见习本', '见习本'), ('普通工', '普通工'), ('技术工一级', '技术工一级'), ('技术工二级', '技术工二级'), ('技术工三级', '技术工三级'), ('技术工四级', '技术工四级'), ('技术工五级', '技术工五级'), ('学徒期', '学徒期')], max_length=20, null=True, verbose_name='职称类别'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='at_post',
            field=models.CharField(choices=[('在职', '在职'), ('离职', '离职')], max_length=10, verbose_name='职工状态'),
        ),
    ]
