# Generated by Django 2.0.13 on 2020-08-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_auto_20200804_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='personal_age',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='personal_state',
            field=models.CharField(choices=[('在职', '在职'), ('离休', '离休'), ('退休', '退休'), ('内退返岗', '内退返岗'), ('内退', '内退'), ('调离', '调离'), ('辞职', '辞职'), ('自动离职', '自动离职'), ('开除', '开除'), ('去世', '去世'), ('解聘', '解聘'), ('疾病不在岗', '疾病不在岗'), ('疾病在岗', '疾病在岗'), ('哺乳假', '哺乳假'), ('拟调离', '拟调离'), ('内部退养', '内部退养'), ('境内研修', '境内研修'), ('挂校人才中心', '挂校人才中心'), ('延聘人员', '延聘人员'), ('离岗待退', '离岗待退'), ('境外研修', '境外研修'), ('借调挂职', '借调挂职'), ('短期用工', '短期用工'), ('病事假', '病事假'), ('停职创办企业', '停职创办企业'), ('其他', '其他'), ('逾期未归', '逾期未归'), ('返聘人员', '返聘人员'), ('异地任职', '异地任职'), ('产假', '产假'), ('后勤集团返岗', '后勤集团返岗')], default='在职', max_length=10, verbose_name='职工状态'),
        ),
    ]
