# Generated by Django 2.0.13 on 2020-09-07 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_auto_20200804_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_start_time', models.DateField(blank=True, null=True, verbose_name='访学开始时间')),
                ('visit_end_time', models.DateField(blank=True, null=True, verbose_name='访学结束时间')),
                ('visit_country', models.CharField(blank=True, max_length=128, null=True, verbose_name='访学国家')),
                ('visit_school', models.CharField(blank=True, max_length=128, null=True, verbose_name='访学学校')),
                ('visit_major', models.CharField(blank=True, max_length=128, null=True, verbose_name='访学专业')),
                ('visit_relate_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.Staff')),
            ],
            options={
                'verbose_name': '访学信息',
                'verbose_name_plural': '访学信息',
            },
        ),
    ]
