# Generated by Django 2.0.13 on 2020-09-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_info',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
    ]
