# Generated by Django 2.0.13 on 2020-09-07 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0016_visit_visit_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_school', models.CharField(blank=True, max_length=128, null=True, verbose_name='学校')),
                ('study_grade', models.CharField(blank=True, max_length=128, null=True, verbose_name='学位')),
                ('study_major', models.CharField(blank=True, max_length=128, null=True, verbose_name='专业')),
                ('study_relate_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.Staff', verbose_name='关联职工')),
            ],
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_relate_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.Staff', verbose_name='关联职工'),
        ),
    ]
